apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservices-chart.fullname" . }}-service-b
spec:
  replicas: {{ .Values.replicaCountB }}
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: "{{ .Values.image.repositoryB }}:{{ .Values.image.tagB }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
